- .github/workflows/pr_stage_test.yml
- .gitignore
- requirements.txt
- setup.py
1. 补充requirements.txt依赖；
2. 增加steup.py；
**Before PR**:
**After PR**:
> [config]: add pre-commit and setup.py

- .github/workflows/lint.yml
- .github/workflows/pr_stage_test.yml
- requirements.txt
- requirements/dev.txt
- requirements/runtime.txt
- requirements/test.txt
- setup.py
> [config]: split requirements with runtime and dev

- llm_web_kit/pipeline/extractor/html/extractor.py
- llm_web_kit/pipeline/extractor/html/recognizer/audio.py
- llm_web_kit/pipeline/extractor/html/recognizer/code.py
- llm_web_kit/pipeline/extractor/html/recognizer/image.py
- llm_web_kit/pipeline/extractor/html/recognizer/list.py
- llm_web_kit/pipeline/extractor/html/recognizer/math.py
- llm_web_kit/pipeline/extractor/html/recognizer/recognizer.py
- llm_web_kit/pipeline/extractor/html/recognizer/table.py
- llm_web_kit/pipeline/extractor/html/recognizer/text.py
- llm_web_kit/pipeline/extractor/html/recognizer/title.py
- llm_web_kit/pipeline/extractor/html/recognizer/video.py
> fix: save extracted content and raw_html simultaneously

- llm_web_kit/pipeline/extractor/html/recognizer/math.py
- requirements/dev.txt
- requirements/runtime.txt
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_math.py
增加html数学公式抽取：
(cchmtl, o_html) -> (ccmath, o_html)
**Before PR**:
**After PR**:
> [feature]: add math extract

- llm_web_kit/pipeline/extractor/html/recognizer/math.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_math.py
1. 数据公式渲染器是从head中的定义获取；
**Before PR**:
**After PR**:
> [feature]: add math render detect method

- llm_web_kit/pipeline/extractor/html/recognizer/table.py
> add table parse

- llm_web_kit/pipeline/extractor/html/recognizer/ccmath.py
- llm_web_kit/pipeline/extractor/html/recognizer/common.py
- llm_web_kit/pipeline/extractor/html/recognizer/recognizer.py
- requirements/runtime.txt
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_math.py
1. ccmath中实现了to_content_list_node方法；
2. 增加了行内行间判断方法get_equation_type；
3. 基类中增加了判断html片段是否是cc标签的方法；
4. 部分使用beautifulsoup解析库的替换为lxml库；
If this PR introduces a new feature, it is better to list some use cases here and …
> [feat]: add to_content_list_node method and get_equation_type

- llm_web_kit/pipeline/extractor/html/recognizer/ccmath.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_math.py
1. 数学公式判断类型contains_math增加latex，mathml，asciimath等类型；
**Before PR**:
**After PR**:
> [feature]: add contains_math

- .pre-commit-config.yaml
- llm_web_kit/pipeline/extractor/html/recognizer/cccode.py
- llm_web_kit/pipeline/extractor/html/recognizer/code/common.py
- llm_web_kit/pipeline/extractor/html/recognizer/code/tag_code.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/cccode/homemade-0.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/cccode/homemade-1.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/cccode/homemade-2.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/cccode/telerik-0.cs
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/cccode/telerik-1.cs
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/cccode/telerik-2.xml
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/cccode/telerik-3.cs
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/cccode/telerik-4.xml
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/cccode/telerik-5.cs
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/cccode/telerik-6.cs
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/cccode/telerik-7.xml
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/cccode/telerik-8.cs
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_code.py
> fix: extract node changed tree structure && feat: add new test case

- llm_web_kit/pipeline/extractor/html/recognizer/recognizer.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/raw_html_attr.html
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_recognizer.py
> feat: get raw_html from user defined html tag

- llm_web_kit/pipeline/extractor/html/recognizer/ccmath.py
- llm_web_kit/pipeline/extractor/html/recognizer/common.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_math.py
1. 增加class=math-container的场景；测试用例待补充；
**Before PR**:
**After PR**:
> feat: add math-container extract

- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_recognizer.py
> test: add test case

- llm_web_kit/pipeline/extractor/html/recognizer/recognizer.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/recognizer/iscctag.html
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_recognizer.py
> fix: add function to test if a html segment contain a cc html tag

- llm_web_kit/pipeline/extractor/html/extractor.py
- llm_web_kit/pipeline/extractor/html/recognizer/cccode.py
- llm_web_kit/pipeline/extractor/html/recognizer/image.py
- llm_web_kit/pipeline/extractor/html/recognizer/recognizer.py
- llm_web_kit/pipeline/extractor/html/recognizer/text.py
- llm_web_kit/pipeline/pipeline_suit.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/recognizer/iscctag.html
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_recognizer.py
> fix: html split by tag

- llm_web_kit/pipeline/extractor/html/recognizer/recognizer.py
- llm_web_kit/pipeline/extractor/html/recognizer/title.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_title.py
> feat: title recognize

- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/tag_math.py
- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/tag_span_mathcontainer.py
- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/tag_span_mathjax.py
- llm_web_kit/pipeline/extractor/html/recognizer/ccmath.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/ccmath/wikipedia_1_math_annotation.html
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_math.py
1. 修了几个bug；
**Before PR**:
**After PR**:
> fix: span math modify

- llm_web_kit/input/datajson.py
- llm_web_kit/pipeline/pipeline.py
- llm_web_kit/pipeline/pipeline_suit.py
- tests/llm_web_kit/pipeline/test_pipeline.py
> fix: test case of pipeline

- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/tag_span_script.py
> feat: add html tag_span_script

- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/tag_span_script.py
1. fix pre-commit问题；
**Before PR**:
**After PR**:
> fix: pre-commit

- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/common.py
- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/tag_math.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_math.py
1. wrap_math方法是对抽取到latex公式做一次格式统一化，本次pr优化这部分的处理逻辑，并补充了相应的测试用例；
**Before …
> fix: wrap_math rm brace handle

- bench/Bench.md
- bench/eval.py
- bench/eval/magic_html.py
- bench/eval/unstructured_eval.py
- bench/html/ccmath/mathjax_equation-numbers.html
- bench/html/ccmath/mathjax_mml-chtml.html
- bench/html/ccmath/mathjax_tex-chtml.html
- bench/html/ccmath/wikipedia_wiki_Variance.html
1. 增加bench的模块，收集不同特征的html，方便快速对比不同的网页抽取工具的效果；
**Before PR**:
**After PR**:
> feat: add bench

- llm_web_kit/pipeline/extractor/html/recognizer/cccode.py
- llm_web_kit/pipeline/extractor/html/recognizer/code/tag_code.py
> fix: extract code fail if table exists

- llm_web_kit/pipeline/extractor/html/recognizer/code/tag_code.py
> fix: [cccode] error when one code tag only

- llm_web_kit/model/code_detector.py
- tests/llm_web_kit/model/test_code_detector.py
> feat: code classification model

- bench/eval.py
- bench/eval/ours.py
- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/tag_common_modify.py
- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/tag_img.py
- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/tag_math.py
- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/tag_script.py
- llm_web_kit/pipeline/extractor/html/recognizer/ccmath.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/ccmath/math_katex_latex_2.html
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_math.py
> fix: add ccmath exception and refine

- llm_web_kit/input/datajson.py
- tests/llm_web_kit/pipeline/test_pipeline_suit.py
> feat: get main html form content list

- llm_web_kit/input/datajson.py
- llm_web_kit/libs/html_utils.py
- llm_web_kit/pipeline/extractor/html/extractor.py
- tests/llm_web_kit/pipeline/test_pipeline_suit.py
> fix: do not add content list node with empty text

- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/tag_asciimath.py
Reverts ccprocessor/llm-webkit-mirror#135
> Revert "fix: tag_asciimath"

- llm_web_kit/input/datajson.py
- llm_web_kit/libs/doc_element_type.py
- llm_web_kit/pipeline/extractor/html/recognizer/cccode.py
- llm_web_kit/pipeline/extractor/html/recognizer/code/common.py
- llm_web_kit/pipeline/extractor/html/recognizer/code/tag_pre.py
- llm_web_kit/pipeline/extractor/html/recognizer/list.py
- llm_web_kit/pipeline/extractor/html/recognizer/recognizer.py
- llm_web_kit/pipeline/extractor/html/recognizer/text.py
- llm_web_kit/pipeline/extractor/html/recognizer/title.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/cccode/mathworks.md
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/cccode/mathworks.txt
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_code.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_title.py
- tests/llm_web_kit/pipeline/test_pipeline_suit.py
> feat: inline code and fix all tests

- llm_web_kit/input/datajson.py
- llm_web_kit/libs/html_utils.py
- tests/llm_web_kit/libs/test_html_utils.py
- tests/llm_web_kit/pipeline/assets/pipline_suit_input/good_data/output_expected/1.main_html.html
- tests/llm_web_kit/pipeline/assets/pipline_suit_input/good_data/output_expected/1.md
- tests/llm_web_kit/pipeline/assets/pipline_suit_input/good_data/output_expected/1.txt
- tests/llm_web_kit/pipeline/test_pipeline_suit.py
> fix: html table to markdown table issue

- bench/html/all.json
- bench/html/cctable/table_1.html
- bench/html/cctable/table_2.html
- bench/html/cctable/table_3.html
- bench/html/cctable/table_4.html
- llm_web_kit/pipeline/extractor/html/extractor.py
- llm_web_kit/pipeline/extractor/html/recognizer/ccmath.py
> bench: add 2 table test data

- llm_web_kit/pipeline/extractor/html/recognizer/text.py
- tests/llm_web_kit/libs/test_html_utils.py
- tests/llm_web_kit/pipeline/assets/pipline_suit_input/good_data/html/math.stackoverflow.html
- tests/llm_web_kit/pipeline/assets/pipline_suit_input/good_data/html_data_input.jsonl
- tests/llm_web_kit/pipeline/extractor/html/recognizer/answer-1.md
- tests/llm_web_kit/pipeline/extractor/html/recognizer/answer-2.txt
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_code.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_para.py
- tests/llm_web_kit/pipeline/test_pipeline_suit.py
> fix: some text lost

- llm_web_kit/input/datajson.py
- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/common.py
- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/tag_asciimath.py
- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/tag_common_modify.py
- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/tag_img.py
- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/tag_math.py
- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/tag_script.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/ccmath/katex_mathjax_1.html
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/ccmath/stackexchange_1_span-math-container_latex_mathjax_1.html
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_math.py
> fix: wrap inline equation

- llm_web_kit/libs/html_utils.py
- llm_web_kit/libs/text_utils.py
- llm_web_kit/pipeline/extractor/html/post_extractor.py
- tests/llm_web_kit/libs/test_text_utils.py
- tests/llm_web_kit/pipeline/assets/pipline_suit_input/html_pipeline_formatter_disable.jsonc
- tests/llm_web_kit/pipeline/extractor/html/test_HTMLStripSpacePostExtractor.py
> feat: Replace consecutive whitespace characters in the text with a single one

- llm_web_kit/pipeline/extractor/html/recognizer/cc_math/common.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/ccmath/libretexts_1_p_latex_mathjax_1.html
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/ccmath/mathjax_tex_chtml_1.html
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_math.py
> fix: inline and interline math wrap rm \(\) and \[\]

- llm_web_kit/pipeline/extractor/html/recognizer/text.py
- tests/llm_web_kit/pipeline/extractor/html/recognizer/assets/recognizer/simple_para.html
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_para.py
> fix: 修复段落提取文本时，节点 tail 中的文本拼接在子元素的文本前

- llm_web_kit/pipeline/extractor/html/recognizer/cccode.py
- llm_web_kit/pipeline/extractor/html/recognizer/code/common.py
- llm_web_kit/pipeline/extractor/html/recognizer/code/tag_code.py
- tests/llm_web_kit/pipeline/assets/pipline_suit_input/good_data/html/csdn_lineno.html
- tests/llm_web_kit/pipeline/assets/pipline_suit_input/good_data/html/doc.html
- tests/llm_web_kit/pipeline/assets/pipline_suit_input/good_data/html_data_input.jsonl
- tests/llm_web_kit/pipeline/assets/pipline_suit_input/good_data/output_expected/csdn_lineno.md
- tests/llm_web_kit/pipeline/extractor/html/recognizer/test_code.py
- tests/llm_web_kit/pipeline/test_pipeline_suit.py
> feat: detect code lineno and remove lineno

- llm_web_kit/tools/cli.py
- requirements/runtime.txt
- setup.py
- tests/llm_web_kit/cli_sdk/assets/empty.json
- tests/llm_web_kit/cli_sdk/assets/input_with_html.json
- tests/llm_web_kit/cli_sdk/assets/input_with_path.json
- tests/llm_web_kit/cli_sdk/assets/invalid.json
- tests/llm_web_kit/cli_sdk/assets/test.html
- tests/llm_web_kit/cli_sdk/test_cli_sdk.py
add magic-html command tool
add cli file in llm_web_kit/tools/cli.py and test case in tests/llm_web_kit/cli_sdk
**Before PR**:
**After PR**:
> feat: add magic-html command tool

- llm_web_kit/model/html_lib/base_func.py
- llm_web_kit/model/html_lib/merge_tags.py
- llm_web_kit/model/html_lib/modify_tags.py
- llm_web_kit/model/html_lib/remove_tags.py
- llm_web_kit/model/html_lib/simplify.py
- llm_web_kit/model/html_lib/unwrap_tags.py
- tests/llm_web_kit/model/html_lib/test_base_func.py
- tests/llm_web_kit/model/html_lib/test_merge_tags.py
- tests/llm_web_kit/model/html_lib/test_modify_tags.py
- tests/llm_web_kit/model/html_lib/test_remove_tags.py
- tests/llm_web_kit/model/html_lib/test_simplify.py
- tests/llm_web_kit/model/html_lib/test_unwrap_tags.py
Add HTML simplify code for HTML classification.
**Before PR**:
**After PR**:
> feat: Add  HTML tag process and simplify for classification algorithm

- llm_web_kit/pipeline/extractor/html/magic_html/extractors/base_extractor.py
- llm_web_kit/pipeline/extractor/html/magic_html/readability_plus.py
> feat: Ignore bad styles in the code

- requirements/runtime.txt
> fix: del unused dependencies

- .github/workflows/pr_stage_test.yml
- bench/Bench.md
- bench/common/metrics.py
- bench/common/result.py
- bench/eval/ours.py
- bench/run.py
- llm_web_kit/libs/statics.py
- requirements/dev.txt
- tests/llm_web_kit/pipeline/extractor/html/test_ContentListStaticsPostExtractor.py
- tests/st/test_st.py
1. 增加集成测试回归到CI中；当前是判断bench/data/origin下的40+测试html需要在回归中都保证抽取成功；（1. 还未对抽取内容进行验证，未来加； 2. code_5.html文件抽取有bug，暂时先跳过，等修复后添加进来）
If this PR introduces a new feature, it is better to list …
> [test]: add st test in CI

- docs/llm_web_kit/model/lang_id.md
- llm_web_kit/config/README.MD
- llm_web_kit/model/lang_id.py
- llm_web_kit/model/resource_utils/download_assets.py
- tests/llm_web_kit/model/resource_utils/test_download_assets.py
- tests/llm_web_kit/model/test_lang_id.py
> lang_id doc

- llm_web_kit/exception/exception.jsonc
- llm_web_kit/exception/exception.py
- tests/llm_web_kit/exception/test_exception_data.py
Make CleanExp inherit from WebKitBaseException
> bugfix: Make CleanExp inherit from WebKitBaseException

- llm_web_kit/model/html_lib/remove_tags.py
- tests/llm_web_kit/model/html_lib/test_remove_tags.py
fix "noscript" tag in html simplify func.
**Before PR**:
**After PR**:
> fix html simplify noscript tag

- .github/workflows/pr_stage_test.yml
- requirements/runtime.txt
1. CI增加了3.11和3.12版本回归（3.13版本目前不支持，安装transformer有报错）；
**Before PR**:
**After …
> [CI]: add python3.12&3.11 env

- .pre-commit-config.yaml
- llm_web_kit/extractor/extractor_chain.py
- llm_web_kit/extractor/html/recognizer/title.py
- llm_web_kit/input/datajson.py
- llm_web_kit/libs/logger.py
- tests/llm_web_kit/input/test_datajson.py
> fix: DataJson construct method do not change outer variable

- .codecov.yml
- bench/run.py
- llm_web_kit/extractor/html/recognizer/cc_math/tag_script.py
- llm_web_kit/extractor/html/recognizer/ccmath.py
- tests/llm_web_kit/extractor/html/recognizer/assets/ccmath/mathtex_script_type.html
- tests/llm_web_kit/extractor/html/recognizer/test_math.py
1. 解决部分场景下math 内容是nonetype；
**Before PR**:
**After PR**:
> [fix]: fix math nonetype

- docs/llm_web_kit/model/quality_model.md
添加质量模型的文档，主要包括接口使用方法，速度测试结果等内容。
> add document of quality model

- llm_web_kit/extractor/html/recognizer/cc_math/common.py
- tests/llm_web_kit/extractor/html/recognizer/test_math.py
> fix:math no text

- llm_web_kit/model/clean_module.py
- llm_web_kit/model/quality_model.py
- llm_web_kit/model/resource_utils/download_assets.py
- tests/llm_web_kit/model/test_clean_module.py
- tests/llm_web_kit/model/test_quality_model.py
add CleanModule to provide general clean function API
covered by testing
> feat: add CleanModule to provide general clean function

- docs/llm_web_kit/model/political.md
- llm_web_kit/model/policical.py
- tests/llm_web_kit/model/test_political.py
根据新的通用清洗要求，在llm_web_kit/model/policical.py中增加一个新的接口函数
> Add a new interface in political model to accommodate the new requirement

- docs/llm_web_kit/model/lang_id.md
> lang_id doc revise

- llm_web_kit/exception/exception.jsonc
- llm_web_kit/exception/exception.py
- llm_web_kit/extractor/html/recognizer/cc_math/tag_asciimath.py
- llm_web_kit/extractor/html/recognizer/cc_math/tag_common_modify.py
- llm_web_kit/extractor/html/recognizer/cc_math/tag_img.py
- llm_web_kit/extractor/html/recognizer/cc_math/tag_math.py
- llm_web_kit/extractor/html/recognizer/cc_math/tag_script.py
- llm_web_kit/extractor/html/recognizer/ccmath.py
- llm_web_kit/extractor/html/recognizer/table.py
- tests/llm_web_kit/exception/test_exception_data.py
- tests/llm_web_kit/extractor/html/recognizer/test_math.py
Exception refactoring.
Exception framework and related reference code.
> Exception refactoring

- llm_web_kit/html_layout_classify/html_layout_classify.md
- llm_web_kit/html_layout_classify/main.py
- llm_web_kit/html_layout_classify/s3/client.py
- llm_web_kit/html_layout_classify/s3/cmd.py
- llm_web_kit/html_layout_classify/s3/conf.py
- llm_web_kit/html_layout_classify/s3/config.py
- llm_web_kit/html_layout_classify/s3/const.py
- llm_web_kit/html_layout_classify/s3/path.py
- llm_web_kit/html_layout_classify/s3/read.py
- llm_web_kit/html_layout_classify/s3/read_resume.py
- llm_web_kit/html_layout_classify/s3/reader.py
- llm_web_kit/html_layout_classify/s3/retry.py
- llm_web_kit/html_layout_classify/s3/retry_utils.py
- llm_web_kit/html_layout_classify/s3/row_fallback.py
- llm_web_kit/html_layout_classify/s3/utils.py
- llm_web_kit/html_layout_classify/s3/write.py
- requirements/runtime.txt
> fead: html_layout_classify/* 模型分类处理 & html_layout_classify.md

- tests/llm_web_kit/model/resource_utils/test_download_assets.py
> fix: simplify test cases by directly setting CACHE_TMP_DIR mock value

- .gitignore
- llm_web_kit/exception/exception.jsonc
- llm_web_kit/exception/exception.py
- llm_web_kit/extractor/html/extractor.py
- llm_web_kit/html_layout_classify/classify-spot.sh
- llm_web_kit/html_layout_classify/classify.sh
- llm_web_kit/html_layout_classify/main.py
- llm_web_kit/html_layout_classify/readme.md
- llm_web_kit/html_layout_classify/server.py
- llm_web_kit/model/quality_model.py
- requirements/dev.txt
- tests/llm_web_kit/model/test_quality_model.py
> feat: page classify

- llm_web_kit/config/cfg_reader.py
- llm_web_kit/config/pipe_tpl/ebook.jsonc
- llm_web_kit/config/pipe_tpl/html-test.jsonc
- llm_web_kit/config/pipe_tpl/html.jsonc
- llm_web_kit/config/pipe_tpl/pdf.jsonc
- llm_web_kit/extractor/html/post_extractor.py
- llm_web_kit/html_layout_classify/classify-spot.sh
- tests/llm_web_kit/extractor/html/recognizer/assets/cccode/mathworks.md
- tests/llm_web_kit/extractor/html/recognizer/assets/cccode/mathworks.txt
- tests/llm_web_kit/extractor/html/recognizer/test_code.py
- tests/llm_web_kit/extractor/html/recognizer/test_text.py
- tests/llm_web_kit/extractor/html/test_HTMLStripSpacePostExtractor.py
- tests/llm_web_kit/extractor/test_extractor_chain.py
- tests/llm_web_kit/extractor/test_extractor_chain_normal.py
> fix: code and text unit test

- README.md
- llm_web_kit/config/cfg_reader.py
- llm_web_kit/extractor/html/extractor.py
- llm_web_kit/libs/logger.py
- llm_web_kit/model/resource_utils/utils.py
- llm_web_kit/simple.py
- tests/llm_web_kit/config/test_cfg_reader.py
- tests/llm_web_kit/test_simple.py
> feat: simple user api to extract html to markdown

- llm_web_kit/extractor/html/extractor.py
> feat: add title to DataJson

- setup.py
setup add config files in dir llm_web_kit.
> build: setup add config files

- llm_web_kit/extractor/html/post_extractor.py
- llm_web_kit/extractor/html/recognizer/list.py
- llm_web_kit/extractor/html/recognizer/text.py
- llm_web_kit/libs/text_utils.py
- tests/llm_web_kit/extractor/html/recognizer/assets/recognizer/test-list-item.html
- tests/llm_web_kit/extractor/html/recognizer/test_list.py
- tests/llm_web_kit/extractor/html/recognizer/test_text.py
- tests/llm_web_kit/extractor/test_extractor_chain.py
- tests/llm_web_kit/libs/test_text_utils.py
> fix: 乱码问题；去掉空的列表内段落

- llm_web_kit/extractor/html/recognizer/code/tag_code.py
- tests/llm_web_kit/extractor/html/recognizer/assets/cccode/cprograming.c
- tests/llm_web_kit/extractor/html/recognizer/assets/cccode/cprograming.html
- tests/llm_web_kit/extractor/html/recognizer/test_code.py
> fix: codes with newline are not inline-codes

- llm_web_kit/html_layout_classify/restart-job.sh
> feat: add slurm job stop script

- llm_web_kit/input/datajson.py
- llm_web_kit/libs/text_utils.py
- tests/llm_web_kit/extractor/assets/extractor_chain_input/good_data/html/math_physicsforums.html
- tests/llm_web_kit/extractor/test_extractor_chain.py
- tests/llm_web_kit/input/test_datajson.py
- tests/llm_web_kit/libs/test_text_utils.py
1. 支持被br标签分割的公式的抽取；
**Before PR**:
**After PR**:
> feat: support formular break by br tag

- llm_web_kit/extractor/html/recognizer/image.py
- tests/llm_web_kit/extractor/html/recognizer/assets/ccimage/svg_e.html
- tests/llm_web_kit/extractor/html/recognizer/test_image.py
> fix: add svg unit test test_image.py & svg 特殊符号异常修复

- tests/llm_web_kit/input/test_datajson.py
优化了test_datajson.py文件中的单测用例；
**Before PR**:
**After PR**:
> fix: add ut

- .pre-commit-config.yaml
- llm_web_kit/extractor/html/recognizer/cccode.py
- llm_web_kit/extractor/html/recognizer/code/classes.py
- llm_web_kit/extractor/html/recognizer/code/common.py
- tests/llm_web_kit/extractor/html/recognizer/assets/cccode/mathorg-0.py
- tests/llm_web_kit/extractor/html/recognizer/assets/cccode/mathorg.html
- tests/llm_web_kit/extractor/html/recognizer/test_code.py
> feat: detect code by classes

- llm_web_kit/extractor/html/recognizer/image.py
- tests/llm_web_kit/extractor/html/recognizer/assets/ccimage/inline_image.html
- tests/llm_web_kit/extractor/html/recognizer/test_image.py
Delete nested images in title.
> feat: Delete nested images in title

- llm_web_kit/html_layout/html_layout_cosin.py
- requirements/runtime.txt
- tests/llm_web_kit/html_layout/assets/cosin.html
- tests/llm_web_kit/html_layout/assets/feature.html
- tests/llm_web_kit/html_layout/test_html_layout_cosin.py
> add layout 聚类算法及单测

- llm_web_kit/extractor/html/recognizer/text.py
- tests/llm_web_kit/extractor/assets/extractor_chain_input/good_data/html/text11.html
- tests/llm_web_kit/extractor/assets/extractor_chain_input/good_data/html/text12.html
- tests/llm_web_kit/extractor/html/recognizer/test_para.py
- tests/llm_web_kit/extractor/html/recognizer/test_text.py
- tests/llm_web_kit/extractor/test_extractor_chain.py
> refactor: 重构解析段落元素逻辑

- tests/llm_web_kit/input/test_pre_data_json.py
> feat: add pre_data_json unit test

- llm_web_kit/main_html_parser/README.md
> docs: update readme.md

- llm_web_kit/main_html_parser/parser/tag_mapping.py
- tests/llm_web_kit/main_html_parser/processor/test_tag_mapping.py
> <feat>: add raw tag html xpath info to element dict

- .github/workflows/lint.yml
add jupyter package in lint workflow.
> feat: add jupyter package in lint workflow.

- jupyter/domain_clustering/README.md
- jupyter/domain_clustering/README_ZH.md
RT
**Before PR**:
**After PR**:
> docs: update domain cluster readme

- jupyter/domain_clustering/README.md
- jupyter/domain_clustering/README_ZH.md
- jupyter/domain_clustering/pipeline/cc_domain_index_gen.py
- jupyter/layout-clustering/choose_domain.ipynb
- jupyter/layout-clustering/layout.ipynb
- jupyter/layout-clustering/layout_index.ipynb
- jupyter/layout-clustering/layout_sim.ipynb
1. 创建 index 时候 read_s3_rows方法使用 stream 读；
**Before PR**:
**After PR**:
> fix: use tream read in cc domain index read

- llm_web_kit/html_layout/html_layout_cosin.py
- tests/llm_web_kit/html_layout/test_html_layout_cosin.py
> fix: get_feature add is_ignore_tag & similarity by html_layout_cosin.py

- llm_web_kit/input/pre_data_json.py
- llm_web_kit/main_html_parser/parser/tag_simplifier.py
- llm_web_kit/main_html_parser/simplify_html/simplify_html.py
- tests/llm_web_kit/main_html_parser/parser/test_tag_simplifier.py
> feat: 精简控制是否获取XPATH

- llm_web_kit/main_html_parser/parser/layout_batch_parser.py
- tests/llm_web_kit/main_html_parser/parser/test_layout_parser.py
> <feat>: add dynamic classid match switch

- llm_web_kit/input/pre_data_json.py
- llm_web_kit/main_html_parser/parser/layout_batch_parser.py
- llm_web_kit/main_html_parser/parser/tag_mapping.py
- tests/llm_web_kit/input/test_pre_data_json.py
- tests/llm_web_kit/main_html_parser/parser/test_layout_parser.py
> <fix>: fix tag map get_feature None error

- llm_web_kit/main_html_parser/parser/tag_mapping.py
- tests/llm_web_kit/main_html_parser/processor/test_tag_mapping.py
> <feat>: add parse_single in MapItemToHtmlTagsParser for single html extraction

- llm_web_kit/input/datajson.py
- llm_web_kit/llm_layout_node_select/cfg.template.jsonc
- llm_web_kit/llm_layout_node_select/main.py
> feat: use http url as markdown image path

- README.md
- llm_web_kit/simple.py
> fix pylint

- docs/llm_web_kit/model/lang_id.md
- docs/llm_web_kit/model/politics_detector.md
- docs/llm_web_kit/model/rule_based_safety_module.md
- llm_web_kit/model/model_impl.py
- llm_web_kit/model/politics_detector.py
- llm_web_kit/model/porn_detector.py
- llm_web_kit/model/unsafe_words_detector.py
- tests/llm_web_kit/model/test_model_impl.py
- tests/llm_web_kit/model/test_politicis_detector.py
> 修改语言检测文档,涉政模型文档,敏感词代码及文档

- bench/config/ours_config.jsonc
- bench/eval/ours.py
- bench/run.py
- jupyter/domain_clustering/README.md
- jupyter/domain_clustering/README_ZH.md
- jupyter/html-pre-dedup/cc_dedup_fir.ipynb
- jupyter/html-pre-dedup/cc_dedup_sec.ipynb
- jupyter/html-pre-dedup/cc_dedup_thr.ipynb
- jupyter/layout-clustering/layout.ipynb
> bench: fix MagicHTMLFIleFormatorExtractor

- llm_web_kit/input/pre_data_json.py
- llm_web_kit/main_html_parser/parser/layout_batch_parser.py
- tests/llm_web_kit/input/test_pre_data_json.py
- tests/llm_web_kit/main_html_parser/parser/test_layout_parser.py
…d fixed id classid strip() bug
If this PR introduces a new feature, it is better to list some use cases here and update …
> <feat>: add some inline tag noise, make the extraction more robust and fixed id classid strip() bug

- llm_web_kit/model/code_detector.py
- requirements/runtime.txt
- tests/llm_web_kit/model/test_code_detector.py
Add fasttext code model to detect code in content.
> feat: add code detect fasttext model

- llm_web_kit/model/math_detector.py
- llm_web_kit/model/model_impl.py
- llm_web_kit/model/model_interface.py
- tests/llm_web_kit/model/test_math_detector.py
- tests/llm_web_kit/model/test_model_impl.py
- tests/llm_web_kit/model/test_model_interface.py
Add math detector model and test cases.
> feat: add math detector model

- README.md
- llm_web_kit/main_html_parser/parser/tag_mapping.py
- tests/llm_web_kit/main_html_parser/processor/test_tag_mapping.py
> <doc>: add extract main html by model response to README.md

- llm_web_kit/libs/standard_utils.py
- requirements/runtime.txt
- tests/llm_web_kit/libs/test_standard_utils.py
> fix: standard_utils.py update json_loads

- llm_web_kit/input/pre_data_json.py
- llm_web_kit/main_html_parser/parser/layout_batch_parser.py
- llm_web_kit/main_html_parser/parser/tag_mapping.py
- tests/llm_web_kit/input/test_pre_data_json.py
> <improv>: modify typical main html similarity threshold to 0.92

- llm_web_kit/main_html_parser/parser/layout_batch_parser.py
> <fix>: fix remove script tail

- llm_web_kit/config/pipe_tpl/noclip_html.jsonc
- llm_web_kit/config/pipe_tpl/noclip_html_test.jsonc
- llm_web_kit/extractor/html/pre_extractor.py
- tests/llm_web_kit/extractor/html/recognizer/test_text.py
> fix: noclip pre-extract problem

- llm_web_kit/main_html_parser/parser/layout_batch_parser.py
> <fix>: fix None error

- README.md
- llm_web_kit/simple.py
- tests/llm_web_kit/simple/test_simple.py
> feat: simple api add language parameter

- llm_web_kit/main_html_parser/parser/layout_batch_parser.py
…han the template
If this PR introduces a new feature, it is better to list some use cases here and update the …
> <fix>: fix element dict layer key error where html has deeper layer than the template

- README.md
- llm_web_kit/main_html_parser/parser/layout_batch_parser.py
- llm_web_kit/simple.py
- tests/llm_web_kit/simple/test_simple.py
> v4.0.1-released

- llm_web_kit/extractor/html/recognizer/cc_math/tag_math.py
- tests/llm_web_kit/extractor/html/recognizer/assets/ccmath/math_percentage.html
- tests/llm_web_kit/extractor/html/recognizer/assets/ccmath/math_percentage_1.html
- tests/llm_web_kit/extractor/html/recognizer/assets/ccmath/math_percentage_inline_1.html
- tests/llm_web_kit/extractor/html/recognizer/test_math.py
> fix: escape '%' in MathML formula v2

- llm_web_kit/extractor/html/post_main_html_processer/post_llm.py
- llm_web_kit/extractor/html/post_main_html_processer/post_mapping.py
- tests/llm_web_kit/extractor/html/post_main_html_processer/post_main_html_processer_demo.py
- tests/llm_web_kit/extractor/html/post_main_html_processer/test_post_llm.py
> fix: add post_main_html_processer_demo.py & update post main html
